name: Deploy use reusable workflow
on:
  pull_request:
    types: [opened, synchronize, reopened, closed]
  issue_comment:
    types: [created]

jobs:
  deploy_dev:
    runs-on: ubuntu-latest
    if: github.event_name == 'issue_comment' && github.event.issue.pull_request && startsWith(github.event.comment.body, '/liquibase ')
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract comment info
        id: extract_comment_info
        run: |
          COMMENT_BODY="${{ github.event.comment.body }}"
          if [[ "$COMMENT_BODY" =~ /liquibase\ ([a-zA-Z0-9_-]+) ]]; then
            STAGE="${BASH_REMATCH[1]}"
            HOST="${BASH_REMATCH[2]}"
            DBNAME="${BASH_REMATCH[3]}"
            echo "stage=$STAGE" >> "$GITHUB_OUTPUT"
			echo "host=$HOST" >> "$GITHUB_OUTPUT"
            echo "db_name=$DBNAME" >> "$GITHUB_OUTPUT"						
          fi

      - name: Call Deploy Workflow
        uses:./.github/workflows/reusable_workflow.yml
        with:
          stage: ${{ steps.extract_comment_info.outputs.stage }}
          host: ${{ steps.extract_comment_info.outputs.host }}
          db_name: ${{ steps.extract_comment_info.outputs.db_name }}
		secrets:
          inherit
